name: Appscan Factory

on:
    # Scan changed files in PRs (diff-aware scanning):
    pull_request: {}
    # Scan on-demand through GitHub Actions interface:
    workflow_dispatch: {}
    # Scan mainline branches and report all findings:
    push:
        branches: ["master", "main"]
    schedule:
        - cron: "0 0 */5 * *"
jobs:
    SAST:
        name: SAST - semgrep-oss
        # If you are self-hosting, change the following `runs-on` value:
        runs-on: ubuntu-latest

        container:
            # A Docker image with Semgrep installed. Do not change this.
            # image: semgrep/semgrep
            # A custom Docker image with Semgrep installed.
            image: ahddry/semgrep-custom:latest

        # Skip any PR created by dependabot to avoid permission issues:
        if: (github.actor != 'dependabot[bot]')

        steps:
            # Fetch project source with GitHub Actions Checkout. Use either v3 or v4.
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Verify installed tools
              run: |
                  semgrep --version
                  visu-semgrep-ci -t
            - name: Install parser's dependencies
              run: |
                  pip install -r requirements.txt
            - name: ignore specific files
              run: |
                  echo ".*" > ".semgrepignore"
                  ls -al
            - name: Run Semgrep
              run: semgrep-custom . .
            - name: Upload semgrep artifact
              uses: actions/upload-artifact@v4
              with:
                  name: semgrep-results
                  path: semgrep-report.json
            - name: Upload report summary
              uses: actions/upload-artifact@v4
              with:
                  name: report-summary
                  path: semgrep-results-summary.txt

    SBOM-SCA:
        name: SBOM - CycloneDX & SCA - Depscan
        runs-on: ubuntu-latest
        if: (github.actor != 'dependabot[bot]')

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"
            - name: Setup Node.js
              uses: actions/setup-node@v4
            - name: Install cdxgen
              run: npm install -g @cyclonedx/cdxgen
            - name: Install depscan
              run: pip install owasp-depscan
            - name: Verify installed tools
              run: |
                  cdxgen -v
                  depscan --version
            - name: Run CycloneDx
              run: cdxgen -o cdxgen-sbom.json
            - name: Run depscan
              run: depscan --no-vuln-table --no-banner --bom cdxgen-sbom.json --reports-dir .
            - name: Upload CycloneDx SBOM
              uses: actions/upload-artifact@v4
              with:
                  name: cdxgen-sbom
                  path: cdxgen-sbom.json
            - name: Upload depscan report
              uses: actions/upload-artifact@v4
              with:
                  name: depscan-report
                  path: depscan-bom.json
    SAST-upload:
        name: Parse and upload SAST results
        runs-on: ubuntu-latest
        needs: SAST
        if: (github.actor != 'dependabot[bot]')

        steps:
            - name: Download semgrep artifact
              uses: actions/download-artifact@v4.1.8
              with:
                  name: semgrep-results
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"
            - name: Get latest release
              id: get_release
              uses: actions/github-script@v7
              with:
                  script: |
                      const response = await github.repos.getLatestRelease({
                          owner: 'Ahddry',
                          repo: 'sast-visu-tools'
                      });
                      const asset = response.data.assets.find(asset => asset.name === 'parsers.zip');
                      return asset.browser_download_url;
            - name: Download and install parser
              run: wget ${{ steps.get_release.outputs.data }} -O parsers.zip && unzip parsers.zip
            # - name: Install parser
            #   run: wget https://github.com/Ahddry/sast-visu-tools/releases/download/0.5.0/parsers.zip -O parsers.zip && unzip parsers.zip
            - name: Install dependencies
              run: pip install -r requirements.txt
            - name: Parse results and upload to database
              env:
                  PROJECT_ID: ${{ secrets.PROJECT_ID }}
                  MONGODB_URL: ${{ secrets.MONGODB_URL }}
                  MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
                  MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
              run: python sast-parser.py semgrep-report.json
            - name: Upload parsed report
              uses: actions/upload-artifact@v4
              with:
                  name: parsed-report
                  path: parsed_file.json
    SBOM-upload:
        name: Parse and upload SBOM results
        runs-on: ubuntu-latest
        needs: SBOM-SCA
        if: (github.actor != 'dependabot[bot]')

        steps:
            - name: Download SBOM artifact
              uses: actions/download-artifact@v4.1.8
              with:
                  name: cdxgen-sbom
            - name: Download depscan artifact
              uses: actions/download-artifact@v4.1.8
              with:
                  name: depscan-report
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"
            - name: Get latest release
              id: get_release
              uses: actions/github-script@v7
              with:
                  script: |
                      const response = await github.repos.getLatestRelease({
                          owner: 'Ahddry',
                          repo: 'sast-visu-tools'
                      });
                      const asset = response.data.assets.find(asset => asset.name === 'parsers.zip');
                      return asset.browser_download_url;
            - name: Download and install parser
              run: wget ${{ steps.get_release.outputs.data }} -O parsers.zip && unzip parsers.zip
            # - name: Install parser
            #   run: wget https://github.com/Ahddry/sast-visu-tools/releases/download/0.5.0/parsers.zip -O parsers.zip && unzip parsers.zip
            - name: Install dependencies
              run: pip install -r requirements.txt
            - name: Parse results and upload to database
              env:
                  PROJECT_ID: ${{ secrets.PROJECT_ID }}
                  MONGODB_URL: ${{ secrets.MONGODB_URL }}
                  MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
                  MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
              run: python sbom-parser.py cdxgen-sbom.json depscan-bom.json
