name: SonarQube Analysis

on:
    push:
        branches:
            - main

jobs:
    sonarqube:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16

            - name: Install Dependencies
              run: npm install

            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
              env:
                  # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            - name: Install OWASP Dependency-Check
              run: |
                  $ VERSION=$(curl -s https://jeremylong.github.io/DependencyCheck/current.txt)
                  curl -Ls "https://github.com/jeremylong/DependencyCheck/releases/download/v$VERSION/dependency-check-$VERSION-release.zip" --output dependency-check.zip

                  unzip dependency-check.zip -d dependency-check
                  chmod +x dependency-check/bin/dependency-check.sh
              shell: bash

            - name: Run Dependency-Check
              run: |
                  dependency-check/bin/dependency-check.sh --scan . --out . --format HTML
              continue-on-error: true

            - name: Upload Dependency-Check Report
              uses: actions/upload-artifact@v2
              with:
                  name: dependency-check-report
                  path: dependency-check-report.html
