# Name of this GitHub Actions workflow.
name: Semgrep OSS scan

on:
    # Scan changed files in PRs (diff-aware scanning):
    pull_request: {}
    # Scan on-demand through GitHub Actions interface:
    workflow_dispatch: {}
    # Scan mainline branches and report all findings:
    push:
        branches: ["master", "main"]
jobs:
    semgrep:
        # User definable name of this GitHub Actions job.
        name: semgrep-oss/scan
        # If you are self-hosting, change the following `runs-on` value:
        runs-on: ubuntu-latest

        container:
            # A Docker image with Semgrep installed. Do not change this.
            image: semgrep/semgrep

        # Skip any PR created by dependabot to avoid permission issues:
        if: (github.actor != 'dependabot[bot]')

        steps:
            # Fetch project source with GitHub Actions Checkout. Use either v3 or v4.
            - uses: actions/checkout@v4
            - name: Download custom ruleset
              # Download the custom Semgrep ruleset from the user's repository.
              run: |
                  wget https://github.com/Ahddry/sast-visu-tools/releases/download/0.3.0/semgrep-custom
                  chmod +x semgrep-custom
                  ls -al
            # - name: Run test Semgrep
            #   run: |
            #       semgrep scan --config auto --json -o semgrep-test.json
            # - name: Upload test semgrep
            #   uses: actions/upload-artifact@v3
            #   with:
            #       name: semgrep-test
            #       path: semgrep-test.json
            - name: Run custom Semgrep
              # Run the custom instance of Semgrep with the custom ruleset.
              run: |
                  ./semgrep-custom . .
            - name: Zip the folder
              run: |
                  folder=$(ls -d 20*/)
                  zip -r output.zip "$folder"

            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                  name: semgrep-results
                  path: output.zip
